language: node_js
os:
- windows
- linux
- osx
node_js:
- '10'
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y fakeroot rpm; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y tree; fi
- npm i -g shx npm-check yarn
before_deploy:
- git config --local user.name "liudonghua123"
- git config --local user.email "liudonghua123@gmail.com"
- git config core.autocrlf true
install:
- npm config set registry="http://registry.npmjs.org/"
- npm i
script:
- CI=false npm run dist
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tree dist; fi
- shx ls -la dist
matrix:
  allow_failures:
  - os: osx
deploy:
  provider: releases
  file:
  - dist/react-material-electron-0.1.0-win32-ia32.zip
  - dist/react-material-electron-0.1.0-win32-x64.zip
  - dist/react-material-electron-0.1.0-win32.exe
  - dist/react-material-electron-0.1.0-linux-ia32.zip
  - dist/react-material-electron-0.1.0-linux-x64.zip
  - dist/react-material-electron-0.1.0-darwin.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
  api-key:
    secure: hsS8fzmIEa8e37m6RabJ43e1nLENWDMAJY0AvbhHR34351X3RQgqwu4Axz4wNc60x52/hEv6yoevndcgafFWkf6C3pbsiZpq+09bsLkS/S3v3ZHSpkbhdvydKhG1qYgSYQh/iZK6P1pB1mgDBORZ3tQvb5yKPRXVQ2OwVSlgY3nM0sSzIO60bb1tyjqgCH/E28qZa6YLxHhoxypU3e9ItAgfh+eMKP+RVoUAAAzuU3cKFwt0i1aLpbDVw71ltCpa11CJ2SK5Nv4+k85TkkVn340hiqhydJBjPkuWObNs8Auf8tlThYrKjea+APaXAKPsOTigi4q9dwRN6P9DjY8y93gCsxnTqtVwl+mNdox+KhMBj++F/JGZTVkCK0k+8heFxvJWBGO0PWx54Rn05KwzssOtmhC2xbbvZUi7WOaiXrYs5fDXZUCfYTV6ds+sb2sewCXFei+Cry0e8Ml4XOf2nvd5hHcXAjaaoXIZCUWnHcK4FLjBELkvjx/8/3NKbSTfQuQiWXGzdykHurDd/7ijxMZlelWYYjafu+RtMUvUfAFTA5TndA3ZIb5+IOalRsJK9dlXEgj8hHhTEdOgJoVXPCjThMl/1a+CB354uShhlSFq9ROOboTGCuMkQ4hYIP6Ql5eOks+6HaMsNiI+s5V+U1c/TkCNECU52u7yQYKrIgE=
